# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py313"
src = [".", "src"]

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D203", # no-blank-line-before-class (incompatible with formatter)
    "D212", # multi-line-summary-first-line (incompatible with formatter)
    "COM812", # incompatible with formatter
    "ISC001", # incompatible with formatter
]

[lint.per-file-ignores]
"tests/**" = ["S101", "ARG001", "F811", "PLR2004", "SLF001", "SIM117", "PLC0415", "D100", "D401", "S108", "PLR2004", "ARG001", "F811", "I001"]
"tests/**/*.py" = ["S101", "ARG001", "F811", "PLR2004", "SLF001", "SIM117", "PLC0415", "D100", "D401", "S108", "I001"]
"tests/*" = ["S101", "ARG001", "F811", "PLR2004", "SLF001", "SIM117", "PLC0415", "D100", "D401", "S108", "I001"]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25

[lint.isort]
known-first-party = ["custom_components.solar_window_system"]
known-third-party = ["homeassistant"]
force-sort-within-sections = true
split-on-trailing-comma = true
