[tool.semantic_release]
version_variable = "custom_components/solar_window_system/manifest.json:version"
branch = "main"
changelog_file = "CHANGELOG.md"
commit_message = "chore(release): {version}"
tag_format = "v{version}"
upload_to_pypi = false
upload_to_release = true

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
