"""Constants for Solar Window System integration."""

DOMAIN = "solar_window_system"

# Entity ID prefix for better organization and future extensions
ENTITY_PREFIX = "sws"
ENTITY_PREFIX_GLOBAL = "sws_global"

# Entry types
ENTRY_TYPE_GROUP = "group"
CONF_GROUP = "group"
CONF_GROUP_NAME = "group_name"

# Global Configuration Entity IDs
GLOBAL_CONFIG_ENTITIES = {
    # Configuration entities
    "window_g_value": {
        "platform": "input_number",
        "name": "Window G-Value",
        "min": 0.1,
        "max": 0.9,
        "step": 0.01,
        "default": 0.5,
        "unit": "",
        "icon": "mdi:window-closed-variant",
        "category": "configuration",
    },
    "window_frame_width": {
        "platform": "input_number",
        "name": "Window Frame Width",
        "min": 0.05,
        "max": 0.5,
        "step": 0.01,
        "default": 0.125,
        "unit": "m",
        "icon": "mdi:square-outline",
        "category": "configuration",
    },
    "window_tilt": {
        "platform": "input_number",
        "name": "Window Tilt",
        "min": 0,
        "max": 90,
        "step": 1,
        "default": 90,
        "unit": "°",
        "icon": "mdi:angle-acute",
        "category": "configuration",
    },
    "diffuse_factor": {
        "platform": "input_number",
        "name": "Diffuse Factor",
        "min": 0.05,
        "max": 0.5,
        "step": 0.01,
        "default": 0.15,
        "unit": "",
        "icon": "mdi:brightness-6",
        "category": "configuration",
    },
    "threshold_direct": {
        "platform": "input_number",
        "name": "Threshold Direct",
        "min": 0,
        "max": 1000,
        "step": 1,
        "default": 200,
        "unit": "W/m²",
        "icon": "mdi:sun-thermometer",
        "category": "configuration",
    },
    "threshold_diffuse": {
        "platform": "input_number",
        "name": "Threshold Diffuse",
        "min": 0,
        "max": 1000,
        "step": 1,
        "default": 150,
        "unit": "W/m²",
        "icon": "mdi:weather-partly-cloudy",
        "category": "configuration",
    },
    "temperature_indoor_base": {
        "platform": "input_number",
        "name": "Temperature Indoor Base",
        "min": 10,
        "max": 30,
        "step": 0.1,
        "default": 23.0,
        "unit": "°C",
        "icon": "mdi:thermometer-chevron-up",
        "category": "configuration",
    },
    "temperature_outdoor_base": {
        "platform": "input_number",
        "name": "Temperature Outdoor Base",
        "min": 10,
        "max": 30,
        "step": 0.1,
        "default": 19.5,
        "unit": "°C",
        "icon": "mdi:thermometer-chevron-down",
        "category": "configuration",
    },
    "weather_warning_sensor": {
        "platform": "input_select",
        "name": "Weather Warning Sensor",
        # Will be populated with binary_sensor and input_boolean entities
        "options": [],
        "default": "",
        "icon": "mdi:weather-lightning",
        "category": "configuration",
    },
    "weather_forecast_temperature_sensor": {
        "platform": "input_select",
        "name": "Weather Forecast Temperature Sensor",
        # Will be populated with temperature sensor entities
        "options": [],
        "default": "",
        "icon": "mdi:thermometer-lines",
        "category": "configuration",
    },
    "scenario_b_enable": {
        "platform": "input_boolean",
        "name": "Scenario B Enable",
        "default": False,
        "icon": "mdi:toggle-switch-off",
        "category": "configuration",
    },
    "scenario_b_temp_indoor": {
        "platform": "input_number",
        "name": "Scenario B Temp Indoor",
        "min": 10,
        "max": 30,
        "step": 0.1,
        "default": 23.5,
        "unit": "°C",
        "icon": "mdi:thermometer-chevron-up",
        "category": "configuration",
    },
    "scenario_b_temp_outdoor": {
        "platform": "input_number",
        "name": "Scenario B Temp Outdoor",
        "min": 10,
        "max": 30,
        "step": 0.1,
        "default": 25.5,
        "unit": "°C",
        "icon": "mdi:thermometer-chevron-down",
        "category": "configuration",
    },
    "scenario_c_enable": {
        "platform": "input_boolean",
        "name": "Scenario C Enable",
        "default": False,
        "icon": "mdi:toggle-switch-off",
        "category": "configuration",
    },
    "scenario_c_temp_indoor": {
        "platform": "input_number",
        "name": "Scenario C Temp Indoor",
        "min": 10,
        "max": 30,
        "step": 0.1,
        "default": 21.5,
        "unit": "°C",
        "icon": "mdi:thermometer-chevron-up",
        "category": "configuration",
    },
    "scenario_c_temp_outdoor": {
        "platform": "input_number",
        "name": "Scenario C Temp Outdoor",
        "min": 10,
        "max": 30,
        "step": 0.1,
        "default": 24.0,
        "unit": "°C",
        "icon": "mdi:thermometer-chevron-down",
        "category": "configuration",
    },
    "scenario_c_temp_forecast": {
        "platform": "input_number",
        "name": "Scenario C Temp Forecast",
        "min": 15,
        "max": 40,
        "step": 0.1,
        "default": 28.5,
        "unit": "°C",
        "icon": "mdi:thermometer-lines",
        "category": "configuration",
    },
    "scenario_c_start_hour": {
        "platform": "input_number",
        "name": "Scenario C Start Hour",
        "min": 0,
        "max": 23,
        "step": 1,
        "default": 9,
        "unit": "h",
        "icon": "mdi:clock-time-four",
        "category": "configuration",
    },
    # Debug entities
    "debug": {
        "platform": "input_text",
        "name": "Debug",
        "max": 255,
        "default": "",
        "icon": "mdi:bug-outline",
        "category": "debug",
    },
    # Sensor entities
    "window_with_shading": {
        "platform": "sensor",
        "name": "Window with Shading",
        "default": 0,
        "unit": "",
        "icon": "mdi:window-shutter",
        "category": "sensor",
    },
    "total_power": {
        "platform": "sensor",
        "name": "Total Power",
        "default": 0,
        "unit": "W",
        "icon": "mdi:lightning-bolt",
        "category": "sensor",
    },
    "total_power_direct": {
        "platform": "sensor",
        "name": "Total Power Direct",
        "default": 0,
        "unit": "W",
        "icon": "mdi:weather-sunny",
        "category": "sensor",
    },
    "total_power_diffuse": {
        "platform": "sensor",
        "name": "Total Power Diffuse",
        "default": 0,
        "unit": "W",
        "icon": "mdi:weather-partly-cloudy",
        "category": "sensor",
    },
}
