name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    needs: [lint, test, validate]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Checkout mit allen Commits und Tags
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      # Python einrichten
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # python-semantic-release installieren
      - name: Install dependencies
        run: pip install python-semantic-release

      # Release ausführen
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          semantic-release publish
