name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # erlaubt es semantic-release, Änderungen zurückzuschreiben

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # wichtig: alle Commits und Tags holen

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install python-semantic-release

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}   # dein PAT mit repo-Rechten
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Actions-Token für Commits
        run: semantic-release publish
